spring:
  datasource:
    hikari:
      maximum-pool-size: 60
      minimum-idle: 20

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  task:
    execution:
      pool:
        core-size: 36
        max-size: 100
        queue-capacity: 10000
    scheduling:
      pool:
        size: 10
